Repository GSG-G10/ShyChat, pull requests merged in 2021-11, with the labels that each got.

#3 2 create server
  server/app.js
  server/index.js
  server/package-lock.json
  server/package.json
Labels: Awaiting Review

#4 create connection file
  server/database/config/build.js
  server/database/config/connection.js
Labels: Awaiting Review

#7 5 database
  server/database/config/build.sql
  server/database/config/fackdata.js
  server/database/config/fakedata.sql
Labels: Awaiting Review

#9 verify | sign token
  server/controllers/utilities/tokenFunctions.js
Labels: Done

#12 10 readme
  README.md
  server/.eslintrc.json
  server/app.js
  server/database/config/build.js
  server/database/config/connection.js
  server/index.js
Labels: Awaiting Review

#15 logout function
  server/controllers/auth/index.js
  server/controllers/auth/logout.js
  server/routes/users.js
Labels: Awaiting Review

#16 sign up router
  package-lock.json
  server/app.js
  server/controllers/auth/index.js
  server/controllers/auth/login.js
  server/controllers/auth/signup.js
  server/controllers/middlewares/checkUserExist.js
  server/controllers/middlewares/index.js
  server/controllers/utilities/hashPassword.js
  server/controllers/utilities/index.js
  server/controllers/utilities/serverSideValidation/index.js
  server/controllers/utilities/serverSideValidation/loginSchema.js
  server/controllers/utilities/serverSideValidation/signUpValidation.js
  server/database/queries/addNewUser.js
  server/database/queries/index.js
  server/package-lock.json
  server/routes/index.js
  server/routes/users.js
Labels: Done

#23 Socket frontEnd
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/logo.png
  client/src/App.css
  client/src/App.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/react-app-env.d.ts
  client/tsconfig.json
  package-lock.json
  server/controllers/auth/editProfile.js
  server/controllers/auth/index.js
  server/controllers/auth/login.js
  server/controllers/middlewares/checkAuth.js
  server/controllers/middlewares/index.js
  server/controllers/utilities/cloudinary.js
  server/controllers/utilities/index.js
  server/database/queries/getUserById.js
  server/database/queries/index.js
  server/database/queries/updateUserProfile.js
  server/package-lock.json
  server/package.json
  server/routes/users.js
Labels: frontEnd

#18 17 edit profile
  server/controllers/auth/editProfile.js
  server/controllers/auth/index.js
  server/controllers/auth/login.js
  server/controllers/middlewares/checkAuth.js
  server/controllers/middlewares/index.js
  server/controllers/utilities/cloudinary.js
  server/controllers/utilities/index.js
  server/database/queries/getUserById.js
  server/database/queries/index.js
  server/database/queries/updateUserProfile.js
  server/package-lock.json
  server/package.json
  server/routes/users.js
Labels: Awaiting Review, backend, route

#26 create send code and verify function
  server/controllers/auth/login.js
  server/controllers/utilities/twilio.js
  server/database/config/build.sql
  server/database/queries/ApproveChange.js
  server/database/queries/index.js
  server/package-lock.json
  server/package.json
  server/routes/users.js
Labels: Done

#27 connect twillio verfication
  server/controllers/auth/login.js
  server/controllers/auth/signup.js
  server/controllers/utilities/index.js
  server/controllers/utilities/twilio.js
  server/database/queries/ApproveChange.js
  server/database/queries/getUserIdByPhoneNumber.js
  server/database/queries/index.js
  server/package-lock.json
  server/routes/users.js
Labels: Awaiting Review, backend, route

#30 redux file structure
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/index.tsx
  client/src/state/action-creators/index.ts
  client/src/state/action-types/index.ts
  client/src/state/actions/index.ts
  client/src/state/index.ts
  client/src/state/reducers/index.ts
  client/src/state/reducers/isLoggoed.ts
  client/src/state/reducers/userInformation.ts
  client/src/state/store.ts
  client/src/util/userInfo.ts
Labels: Awaiting Review, frontEnd

#31 Revert 30 redux structure
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/logo.png
  client/src/App.css
  client/src/App.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/react-app-env.d.ts
  client/tsconfig.json
  server/controllers/utilities/serverSideValidation/loginSchema.js
Labels: Done

#19 socket at backend
  .vscode/settings.json
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/Chat.tsx
  client/src/chat.intro.tsx
  client/src/state/reducers/index.ts
  server/app.js
  server/controllers/chat/index.js
  server/controllers/conversation/index.js
  server/controllers/utilities/serverSideValidation/signUpValidation.js
  server/database/config/build.sql
  server/database/config/fakedata.sql
  server/database/queries/chat/addNewMessage.js
  server/database/queries/chat/addNewParticipent.js
  server/database/queries/chat/checkExistChat.js
  server/database/queries/chat/createNewChat.js
  server/database/queries/chat/index.js
  server/database/queries/index.js
  server/index.js
  server/package-lock.json
  server/package.json
  server/socket/index.js
Labels: Done

#34 Customize axios
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/service/config.json
  client/src/service/errorAlert.tsx
  client/src/service/httpService.ts
  client/src/state/action-creators/index.ts
  client/src/state/action-types/index.ts
  client/src/state/actions/index.ts
  client/src/state/reducers/index.ts
  client/src/state/reducers/showError.ts
  client/tsconfig.json
Labels: Awaiting Review

#35 git user conversations query
  server/database/queries/getUserConversations.js
Labels: Done

#41 sign up form
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App/index.tsx
  client/src/App/style.ts
  client/src/components/common/Img.tsx
  client/src/components/common/Input.tsx
  client/src/pages/signUp/SignUpForm.tsx
  client/src/pages/signUp/index.tsx
  client/src/pages/signUp/schema.ts
  client/src/pages/signUp/style.ts
  client/src/react-app-env.d.ts
  client/src/util/customizeStyle.ts
  client/src/util/images/signup.jpg
Labels: Awaiting Review

#37 git conversation messages query
  server/database/config/fakedata.sql
  server/database/queries/chat/getChatMessages.js
  server/database/queries/chat/getUserConversations.js
  server/database/queries/chat/index.js
  server/database/queries/index.js
Labels: Done

#42 search route
  server/.gitignore
  server/controllers/user/index.js
  server/database/config/fakedata.sql
  server/database/queries/chat/addNewParticipant.js
  server/database/queries/chat/index.js
  server/database/queries/index.js
  server/database/queries/searchUsersByPhone.js
  server/package-lock.json
  server/routes/users.js
Labels: Awaiting Review

#38 contact
  client/package-lock.json
  client/src/App.css
  client/src/App.tsx
  client/src/components/cantact.tsx
Labels: Awaiting Review
