Repository GSG-G10/ShyChat, pull requests merged in 2021-12, with the labels that each got.

#43 Edit profile
  client/package-lock.json
  client/src/App.css
  client/src/App/style.ts
  client/src/components/common/Input.tsx
  client/src/index.css
  client/src/pages/profile/editProfile.tsx
  client/src/pages/profile/editProfileSection.tsx
  client/src/pages/profile/style.ts
  client/src/state/action-creators/index.ts
  client/src/state/action-types/index.ts
  client/src/util/images/logo.png
  client/src/util/previewFile.ts
  server/controllers/auth/editProfile.js
  server/controllers/auth/login.js
  server/controllers/conversation/index.js
  server/controllers/utilities/twilio.js
  server/database/config/build.sql
  server/database/queries/checkPhoneQuery.js
  server/database/queries/getUserIdByPhoneNumber.js
Labels: Done

#48 fix all problems in all files with eslint config
  client/.env
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/App/Home.tsx
  client/src/App/Login.tsx
  client/src/App/ProtectedRoute.tsx
  client/src/App/index.tsx
  client/src/App/style.ts
  client/src/components/cantact.tsx
  client/src/components/common/Img.tsx
  client/src/pages/login/index.tsx
  client/src/pages/profile/editProfile.tsx
  client/src/pages/signUp/index.tsx
  client/src/pages/verify/index.tsx
  client/src/service/ErrorAlert.tsx
  client/src/state/action-types/index.ts
Labels: Done, documentation

#50 edit login
  client/src/App/index.tsx
  client/src/pages/home/index.tsx
  client/src/pages/login/LoginForm.tsx
  server/database/config/fakedata.sql
Labels: Done

#51 Edit login
  client/src/App/ProtectedRoute.tsx
  client/src/App/index.tsx
  client/src/pages/login/LoginForm.tsx
  client/src/pages/profile/index.tsx
  client/src/pages/signUp/SignUpForm.tsx
Labels: Done

#52 Home page
  client/src/components/cantact.tsx
  client/src/pages/home/ContactsSection.tsx
  client/src/pages/home/index.tsx
  client/src/pages/login/LoginForm.tsx
  client/src/pages/verify/VerifyForm.tsx
  client/src/state/reducers/isLoggoed.ts
  server/controllers/auth/getContacts.js
  server/controllers/middlewares/setCookie.js
  server/controllers/middlewares/validatePassword.js
  server/routes/users.js
Labels: Done

#53 style for home page
  client/src/components/cantact.tsx
  client/src/pages/home/ContactsSection.tsx
  client/src/pages/home/index.tsx
  client/src/pages/home/style.ts
Labels: Done

#54 delete test contacts
  client/src/pages/home/ContactsSection.tsx
Labels: Done

#55 user nav
  client/src/components/common/userNav.tsx
  client/src/pages/home/ContactsSection.tsx
  client/src/pages/home/index.tsx
Labels: Done

#59 Home page
  client/src/components/cantact.tsx
  client/src/components/common/Input.tsx
  client/src/components/common/userNav.tsx
  client/src/index.css
  client/src/pages/home/ContactsSection.tsx
  client/src/pages/home/index.tsx
  client/src/pages/home/style.ts
  client/src/state/action-creators/index.ts
  client/src/state/action-types/index.ts
  client/src/state/actions/index.ts
  client/src/state/reducers/currentChatId.ts
  client/src/state/reducers/index.ts
  client/src/util/images/chatBackGround.jpg
  client/src/util/images/customImage.png
  server/controllers/chat/getMessages.js
  server/database/config/fake.sql
  server/routes/users.js
Labels: Awaiting Review

#58 edit in recieve message in socket
  server/controllers/chat/index.js
  server/database/config/fake.sql
  server/database/queries/chat/checkExistChat.js
  server/index.js
  server/socket/index.js
Labels: Done

#60 Socket-frontEnd
  client/src/pages/home/index.tsx
  client/src/pages/home/style.ts
  server/socket/index.js
Labels: Done

#57 create search component
  client/.env
  client/package-lock.json
  client/src/components/Search.tsx
  client/src/index.tsx
  client/src/service/ErrorAlert.tsx
  server/database/queries/searchUsersByPhone.js
  server/package-lock.json
Labels: In Progress

#61 Front messages
  .env
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/Chat.tsx
  client/src/chat.intro.tsx
  client/src/pages/home/index.tsx
  client/src/pages/home/messages.css
  client/src/pages/home/style.ts
  package-lock.json
  package.json
  server/package-lock.json
  server/socket/index.js
Labels: In Progress

#62 merge component in the right way
  client/src/components/Search.tsx
  client/src/components/cantact.tsx
  client/src/index.tsx
  client/src/pages/home/ContactsSection.tsx
  client/src/pages/home/style.ts
Labels: Done

#65 for deploy
  server/app.js
Labels: Done

#64 logout component
  client/src/components/Logout.tsx
Labels: In Progress

#69 Final touch
  client/src/components/common/Input.tsx
  client/src/pages/home/ContactsSection.tsx
  client/src/pages/home/index.tsx
Labels: Done
